import Head from "next/head";
import {
  Button,
  Card,
  Divider,
  Htag,
  IconButton,
  Input,
  Paragraph,
} from "../../components";
import { FaUserCircle } from "react-icons/fa";
import styles from "./Auth.module.css";
import Link from "next/link";

const Auth: React.FC = (): JSX.Element => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Авторизация</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Card className={styles.auth}>
        <FaUserCircle className={styles.userIcon} />
        <Htag tag='h1'>Авторизация</Htag>
        <Input placeholder='Логин или почта' />
        <Input placeholder='Пароль' />
        <Button color='blue'>Войти</Button>
        <Paragraph color='gray' size='md'>
          ИЛИ
        </Paragraph>
        <IconButton variant='bold' icon='googleIcon'>
          Войти черезе google
        </IconButton>

        <Divider />
        <div className={styles.forgotPasswordAndRegistration}>
          <Link href='#'>
            <a>Забыли пароль ?</a>
          </Link>

          <Link href='#'>
            <a>Создать учетную запись</a>
          </Link>
        </div>
      </Card>
    </div>
  );
};

export default Auth;
