import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Button, Input } from "../components";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Главная</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div
        style={{
          display: "flex",
          gap: 10,
          maxWidth: 1140,
          margin: "10px auto",
        }}
      >
        <Button>Синяя кнопка</Button>
        <Button color='red'>Красная кнопка</Button>
        <Button color='pink'>Розовая кнопка</Button>
        <Button color='gray'>Серая кнопка</Button>
        <Button color='green'>Зеленая кнопка</Button>

        <Input type='text' placeholder='Введите логин' />
        <Input type='password' placeholder='Введите пароль' />
      </div>
    </div>
  );
};

export default Home;
